package main

import (
	"github.com/xenking/kitsu-media-server/pkg/config"
	"github.com/xenking/kitsu-media-server/pkg/db"
	"github.com/xenking/kitsu-media-server/pkg/handler"
	"github.com/xenking/kitsu-media-server/pkg/router"
	"github.com/xenking/kitsu-media-server/pkg/store"

	//echoSwagger "github.com/swaggo/echo-swagger"   // echo-swagger middleware
	//_ "github.com/xenking/kitsu-media-server/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Kitsu Media swagger API
// @version 1.0
// @description API for kitsu.media
// @title Kitsu Media API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

func main() {
	cfg := new(config.Config)

	cfg.Init()
	r := router.New()

	//r.GET("/swagger/*", echoSwagger.WrapHandler)

	v1 := r.Group("/api")

	d := db.New(cfg)
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewArticleStore(d)
	ms := store.NewMediaStore(d)
	h := handler.NewHandler(us, as, ms)
	h.Register(v1)
	r.Logger.Fatal(r.Start(cfg.Server.Host + ":" + cfg.Server.Port))
}
